services:
  postgres:
    extends:
      file: ../ecr-viewer/docker-compose.yaml
      service: postgres
    profiles: ["", "azure", "aws"]
  sqlserver:
    extends:
      file: ../ecr-viewer/docker-compose.yaml
      service: sqlserver
    profiles: ["sqlserver"]
  aws-storage:
    extends:
      file: ../ecr-viewer/docker-compose.yaml
      service: aws-storage
    profiles: ["aws"]
  azure-storage:
    extends:
      file: ../ecr-viewer/docker-compose.yaml
      service: azure-storage
    profiles: ["", "azure"]
  ecr-viewer:
    extends:
      file: ../ecr-viewer/docker-compose.yaml
      service: ecr-viewer
    profiles: ["", "azure", "aws", "sqlserver"]
    environment:
      - CONFIG_NAME=AZURE_PG_NON_INTEGRATED
  orchestration-service:
    platform: linux/amd64
    build:
      context: .
    depends_on:
      [
        validation-service,
        fhir-converter-service,
        ingestion-service,
        trigger-code-reference-service,
        message-parser-service,
        ecr-viewer,
      ]
    ports:
      - "${ORCHESTRATION_PORT_NUMBER}:8080"
    logging:
      driver: "json-file"
    env_file:
      - .env
    environment:
      - OTEL_TRACES_EXPORTER=none
      - OTEL_METRICS_EXPORTER=none
  validation-service:
    platform: linux/amd64
    build:
      context: ../validation
    ports:
      - "${VALIDATION_PORT_NUMBER}:8080"
    logging:
      driver: "json-file"
  fhir-converter-service:
    platform: linux/amd64
    build:
      context: ../fhir-converter
    ports:
      - "${FHIR_CONVERTER_PORT_NUMBER}:8080"
    logging:
      driver: "json-file"
  ingestion-service:
    platform: linux/amd64
    build:
      context: ../ingestion
    ports:
      - "${INGESTION_PORT_NUMBER}:8080"
    logging:
      driver: "json-file"
    environment:
      SMARTY_AUTH_ID: ${SMARTY_AUTH_ID}
      SMARTY_AUTH_TOKEN: ${SMARTY_AUTH_TOKEN}
  message-parser-service:
    platform: linux/amd64
    build:
      context: ../message-parser
    ports:
      - "${MESSAGE_PARSER_PORT_NUMBER}:8080"
    logging:
      driver: "json-file"
  trigger-code-reference-service:
    platform: linux/amd64
    build:
      context: ../trigger-code-reference
    ports:
      - "${TRIGGER_CODE_REFERENCE_PORT_NUMBER}:8080"
    logging:
      driver: "json-file"
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: "jaeger"
    volumes:
      - "./jaeger-ui.json:/etc/jaeger/jaeger-ui.json"
    command: --query.ui-config /etc/jaeger/jaeger-ui.json
    ports:
      - "16686:16686" # serves frontend and queries
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus.yaml:/etc/prometheus/prometheus.yaml"
      - "prom_data:/prometheus"
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: "otel-collector"
    volumes:
      - "./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml"
    command: ["--config=/etc/otelcol-contrib/config.yaml"]
    ports:
      - "8888:8888" # Prometheus metrics exposed by collector
      - "8889:8889" # Endpoint prometheus will scrape
      - "4317:4317" # gRPC OTLP receiver
      - "4318:4318" # HTTP OTLP receiver
    depends_on:
      - jaeger
      - prometheus
  grafana:
    image: grafana/grafana-oss
    ports:
      - "4000:3000"
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/datasources/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  prom_data:
  grafana_data:
  db:
  azure-data:
  aws-data:
