on:
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write
  issues: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          # PAT token required to trigger createNewRelease
          token: ${{ secrets.RELEASE_PLEASE_PAT }}
          # this is a built-in strategy in release-please, see "Action Inputs"
          # for more options
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
